### PR TITLE
Add BitKeep Wallet to support Terra Dapps 

### PR DESCRIPTION
**Pull request by bitkeepwallet**
Like MathWallet with chrome extension type.

### CODE REVIEW

**Comment by iamssen** [comment]
@bitkeepwallet is your app? https://apps.apple.com/kr/app/bitkeep/id1395301115 can I test testflight version?

**Comment by bitkeepwallet** [comment]
Yes Please







------------------ Original ------------------
From: Seo Yeon, Lee ***@***.***&gt;
Date: Thu, Aug 12, 2021 4:55 PM
To: terra-money/wallet-provider ***@***.***&gt;
Cc: bitkeepwallet ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [terra-money/wallet-provider] Add BitKeep Wallet to support Terra Dapps  (#13)

**Comment by bitkeepwallet** [comment]
> @bitkeepwallet is your app? https://apps.apple.com/kr/app/bitkeep/id1395301115 can I test testflight version?

we will release this weekend to TestFlight with Terra supported.Then you can test it.

**Comment by iamssen** [comment]
@bitkeepwallet I added a new option to support the chrome compatible wallet development. Please refer to these links.

- Guide <https://github.com/terra-money/wallet-provider/tree/feature/chrome-extension-compatible-wallets#for-chrome-extension-compatible-wallet-developers>
- PR <https://github.com/terra-money/wallet-provider/pull/14>

You can install the test version of `wallet-provider`

```sh
yarn add @terra-money/wallet-provider@canary # or @1.4.0-alpha.1
```

And make a test dApp for your wallet development

```
<WalletProvider
  dangerously__chromeExtensionCompatibleBrowserCheck={(userAgent) =>
    /BitKeep/.test(userAgent)
  }
>
  ...
</WalletProvider>
```

**Pull request closed without merging**
